// ©AngelaMos | 2026
// knowngoods.go

package audit

var KnownGoodProcesses = map[string]string{
	"systemd":                              "init system and service manager",
	"systemd-journald":                     "journal logging daemon",
	"systemd-logind":                       "login manager",
	"systemd-udevd":                        "device manager",
	"systemd-resolved":                     "network name resolution",
	"systemd-timesyncd":                    "time synchronization",
	"systemd-networkd":                     "network configuration",
	"systemd-oomd":                         "out-of-memory killer daemon",
	"systemd-homed":                        "home directory manager",
	"systemd-machined":                     "virtual machine and container manager",
	"systemd-coredump":                     "core dump handler",
	"systemd-userdbd":                      "user database service",
	"systemd-hostnamed":                    "hostname service",
	"systemd-localed":                      "locale service",
	"systemd-timedated":                    "time and date service",
	"systemd-portabled":                    "portable service manager",
	"systemd-importd":                      "disk image importer",
	"systemd-sleep":                        "sleep/suspend handler",
	"plasmashell":                          "kde plasma desktop shell",
	"kwin_wayland":                         "kde window manager wayland",
	"kwin_x11":                             "kde window manager x11",
	"kded5":                                "kde daemon version 5",
	"kded6":                                "kde daemon version 6",
	"kactivitymanagerd":                    "kde activity manager",
	"kglobalaccel5":                        "kde global keyboard shortcuts v5",
	"kglobalaccel6":                        "kde global keyboard shortcuts v6",
	"ksmserver":                            "kde session manager",
	"kscreen_backend_launcher":             "kde screen configuration backend",
	"ksystemstats":                         "kde system statistics collector",
	"polkit-kde-authentication-agent-1":    "kde polkit authentication agent",
	"xdg-desktop-portal-kde":               "kde desktop portal",
	"baloo_file":                           "kde file indexer",
	"baloo_file_extractor":                 "kde file content extractor",
	"kwalletd5":                            "kde wallet manager v5",
	"kwalletd6":                            "kde wallet manager v6",
	"spectacle":                            "kde screenshot utility",
	"dolphin":                              "kde file manager",
	"konsole":                              "kde terminal emulator",
	"korganizer":                           "kde organizer and calendar",
	"kmail":                                "kde mail client",
	"kwrite":                               "kde text editor",
	"kate":                                 "kde advanced text editor",
	"ark":                                  "kde archive manager",
	"gwenview":                             "kde image viewer",
	"okular":                               "kde document viewer",
	"plasma-browser-integration-host":      "kde browser integration",
	"discover":                             "kde software center",
	"ksystemlog":                           "kde system log viewer",
	"powerdevil":                           "kde power management",
	"bluedevil":                            "kde bluetooth manager",
	"kdeconnectd":                          "kde connect daemon",
	"kalendarac":                           "kde calendar alarm client",
	"kioworker":                            "kde io worker process",
	"kiod5":                                "kde io daemon v5",
	"kiod6":                                "kde io daemon v6",
	"klauncher":                            "kde launcher service",
	"krunner":                              "kde quick launcher",
	"plasma-discover-notifier":             "kde update notifier",
	"plasma_session":                       "kde plasma session process",
	"plasma-systemmonitor":                 "kde system monitor",
	"drkonqi":                              "kde crash handler",
	"Xwayland":                             "x11 compatibility layer for wayland",
	"Xorg":                                 "x11 display server",
	"xdg-desktop-portal":                   "desktop portal service",
	"xdg-document-portal":                  "document portal service",
	"xdg-permission-store":                 "permission store service",
	"dbus-daemon":                          "message bus daemon",
	"dbus-broker":                          "message bus broker",
	"dbus-launch":                          "dbus session launcher",
	"pipewire":                             "multimedia framework",
	"wireplumber":                          "pipewire session manager",
	"pipewire-pulse":                       "pulseaudio compatibility layer",
	"pulseaudio":                           "sound server",
	"NetworkManager":                       "network connection manager",
	"wpa_supplicant":                       "wifi authentication",
	"dhclient":                             "dhcp client",
	"dhcpcd":                               "dhcp client daemon",
	"avahi-daemon":                         "mdns/dns-sd service discovery",
	"dockerd":                              "docker daemon",
	"containerd":                           "container runtime",
	"containerd-shim-runc-v2":              "container shim",
	"docker-proxy":                         "docker network proxy",
	"runc":                                 "oci container runtime",
	"cron":                                 "job scheduler",
	"crond":                                "job scheduler daemon",
	"rsyslogd":                             "system log daemon",
	"syslogd":                              "system log daemon legacy",
	"polkitd":                              "policy kit daemon",
	"udisksd":                              "disk management daemon",
	"cupsd":                                "printing system daemon",
	"cups-browsed":                         "printer browser daemon",
	"smartd":                               "disk health monitoring",
	"irqbalance":                           "interrupt balancer",
	"accounts-daemon":                      "user account service",
	"rtkit-daemon":                         "realtime kit daemon",
	"colord":                               "color management daemon",
	"fwupd":                                "firmware update daemon",
	"thermald":                             "thermal management daemon",
	"mcelog":                               "machine check error logger",
	"earlyoom":                             "early oom daemon",
	"packagekitd":                          "package management service",
	"snapd":                                "snap package daemon",
	"flatpak-system-helper":                "flatpak system helper",
	"flatpak-session-helper":               "flatpak session helper",
	"power-profiles-daemon":                "power profiles service",
	"switcheroo-control":                   "gpu switching service",
	"low-memory-monitor":                   "low memory monitor",
	"iio-sensor-proxy":                     "sensor proxy service",
	"boltd":                                "thunderbolt device manager",
	"upowerd":                              "power management daemon",
	"geoclue":                              "geolocation service",
	"ModemManager":                         "modem management daemon",
	"apparmor_parser":                      "apparmor policy parser",
	"auditd":                               "audit framework daemon",
	"sudo":                                 "privilege escalation",
	"sshd":                                 "secure shell server",
	"gpg-agent":                            "gnupg key agent",
	"ssh-agent":                            "ssh key agent",
	"gnome-keyring-daemon":                 "credential storage daemon",
	"pam":                                  "pluggable authentication module",
	"udevd":                                "device manager daemon",
	"acpid":                                "acpi event daemon",
	"pciback":                              "pci device passthrough",
	"nvidia-persistenced":                  "nvidia persistence daemon",
	"nvidia-smi":                           "nvidia system management interface",
	"nvidia-powerd":                        "nvidia power daemon",
	"bluetoothd":                           "bluetooth daemon",
	"dconf-service":                        "dconf configuration service",
	"at-spi-bus-launcher":                  "accessibility bus launcher",
	"at-spi2-registryd":                    "accessibility registry daemon",
	"gvfsd":                                "gnome virtual filesystem daemon",
	"gvfsd-fuse":                           "gnome vfs fuse mount",
	"gvfsd-metadata":                       "gnome vfs metadata service",
	"gvfs-udisks2-volume-monitor":          "gnome vfs disk volume monitor",
	"gvfs-gphoto2-volume-monitor":          "gnome vfs camera monitor",
	"gvfs-mtp-volume-monitor":              "gnome vfs mtp device monitor",
	"gvfs-afc-volume-monitor":              "gnome vfs apple device monitor",
	"evolution-data-server":                "pim data service",
	"evolution-calendar-factory":           "calendar data factory",
	"evolution-source-registry":            "data source registry",
	"evolution-addressbook-factory":        "addressbook data factory",
	"tracker-miner-fs-3":                   "file system indexer",
	"tracker-miner-fs":                     "file system indexer legacy",
	"tracker-extract-3":                    "metadata extractor",
	"tracker-store":                        "metadata store",
	"xdg-user-dirs-update":                 "user directories updater",
	"bash":                                 "bourne-again shell",
	"zsh":                                  "z shell",
	"sh":                                   "posix shell",
	"dash":                                 "debian almquist shell",
	"fish":                                 "friendly interactive shell",
	"tmux":                                 "terminal multiplexer server",
	"tmux: server":                         "terminal multiplexer server process",
	"screen":                               "terminal multiplexer",
	"vim":                                  "vi improved text editor",
	"nvim":                                 "neovim text editor",
	"code":                                 "visual studio code",
	"claude":                               "claude ai assistant",
	"chrome":                               "google chrome browser",
	"chromium":                             "chromium browser",
	"firefox":                              "mozilla firefox browser",
	"firefox-esr":                          "mozilla firefox esr browser",
	"thunderbird":                          "mozilla thunderbird mail",
	"steam":                                "steam gaming client",
	"steamwebhelper":                       "steam web helper",
	"make":                                 "build automation tool",
	"gcc":                                  "gnu c compiler",
	"g++":                                  "gnu c++ compiler",
	"cc1":                                  "c compiler backend",
	"cc1plus":                              "c++ compiler backend",
	"as":                                   "gnu assembler",
	"ld":                                   "gnu linker",
	"go":                                   "go programming language",
	"gopls":                                "go language server",
	"node":                                 "nodejs runtime",
	"python3":                              "python 3 interpreter",
	"python":                               "python interpreter",
	"uv":                                   "python package manager",
	"pnpm":                                 "nodejs package manager",
	"npm":                                  "nodejs package manager legacy",
	"cargo":                                "rust package manager",
	"rustc":                                "rust compiler",
	"rust-analyzer":                        "rust language server",
	"clangd":                               "c/c++ language server",
	"top":                                  "system monitor",
	"htop":                                 "interactive process viewer",
	"btop":                                 "system resource monitor",
	"journalctl":                           "journal log viewer",
	"gpg":                                  "gnupg encryption tool",
	"ssh":                                  "secure shell client",
	"scp":                                  "secure copy",
	"rsync":                                "remote sync tool",
	"tar":                                  "archive utility",
	"gzip":                                 "compression utility",
	"bzip2":                                "compression utility",
	"xz":                                   "compression utility",
	"unzip":                                "zip extraction utility",
	"zip":                                  "zip archive utility",
	"wget":                                 "network downloader",
	"curl":                                 "url transfer tool",
	"git":                                  "version control system",
	"man":                                  "manual page viewer",
	"less":                                 "file pager",
	"more":                                 "file pager legacy",
	"cat":                                  "file concatenation",
	"grep":                                 "pattern search",
	"sed":                                  "stream editor",
	"awk":                                  "text processing language",
	"find":                                 "file search utility",
	"xargs":                                "argument builder",
	"sort":                                 "line sorter",
	"uniq":                                 "duplicate filter",
	"wc":                                   "word count",
	"head":                                 "file head viewer",
	"tail":                                 "file tail viewer",
	"tee":                                  "output splitter",
	"cut":                                  "field extractor",
	"tr":                                   "character translator",
	"diff":                                 "file comparison",
	"patch":                                "patch applier",
	"strace":                               "system call tracer",
	"ltrace":                               "library call tracer",
	"lsof":                                 "open file lister",
	"ss":                                   "socket statistics",
	"ip":                                   "network configuration",
	"ping":                                 "network connectivity test",
	"traceroute":                           "network route tracer",
	"dig":                                  "dns lookup utility",
	"nslookup":                             "dns query tool",
	"mount":                                "filesystem mounter",
	"umount":                               "filesystem unmounter",
	"fsck":                                 "filesystem checker",
	"mkfs":                                 "filesystem creator",
	"fdisk":                                "partition editor",
	"lvm":                                  "logical volume manager",
	"dmsetup":                              "device mapper setup",
	"mdadm":                                "raid management",
	"cryptsetup":                           "disk encryption",
	"systemctl":                            "systemd control",
	"loginctl":                             "login manager control",
	"journald":                             "journal daemon alias",
	"agetty":                               "terminal login prompt",
	"getty":                                 "terminal login prompt legacy",
	"login":                                "user login program",
	"su":                                   "switch user",
	"passwd":                               "password changer",
	"chown":                                "ownership changer",
	"chmod":                                "permission changer",
	"cp":                                   "file copy",
	"mv":                                   "file move",
	"rm":                                   "file remove",
	"ln":                                   "link creator",
	"mkdir":                                "directory creator",
	"rmdir":                                "directory remover",
	"ls":                                   "directory lister",
	"stat":                                 "file status",
	"file":                                 "file type identifier",
	"du":                                   "disk usage calculator",
	"df":                                   "disk free reporter",
	"free":                                 "memory usage reporter",
	"ps":                                   "process status",
	"kill":                                 "signal sender",
	"killall":                              "named signal sender",
	"nice":                                 "priority scheduler",
	"renice":                               "priority modifier",
	"nohup":                                "hangup immune executor",
	"env":                                  "environment runner",
	"xdg-open":                             "default application opener",
	"update-alternatives":                  "alternatives manager",
	"dpkg":                                 "debian package manager",
	"apt":                                  "package manager frontend",
	"apt-get":                              "package manager",
	"aptitude":                             "package manager advanced",
}
